name: Build libnstool

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d3fau4/nx-dev
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - name: Build app
      run: |
        mkdir build-cmake
        cmake -G "Unix Makefiles" --toolchain=DevkitA64Libnx.cmake -S . -B build-cmake
        cmake --build build-cmake
